#!/usr/bin/env python3
"""
Step 22: Quasar-Galaxy Association Test
=======================================
Executes the empirical association test that motivated Arp's
original statistical argument: whether high-redshift quasars are
over-dense in the immediate vicinity of low-redshift galaxies
relative to random fields.

For each Arp host galaxy the step resolves its position through
Simbad and performs a VizieR cone search of the Million Quasars
catalogue (Milliquas, VII/290; Flesch 2021) within a fixed radius
matched to the pair's separation scale, counting spectroscopically
confirmed quasar-class objects — catalogue classes Q (type-I
broad-line quasar), A (type-I Seyfert/AGN), B (BL Lac) and K
(type-II narrow-line quasar); class N carries a documented
NELG/ELG/LINER residue and photometric candidates are excluded.
The host galaxy's own catalogue entry is removed by name, and the
catalogued companions themselves — resolved to archive positions
by step_20 — are excluded from the primary count, since the pairs
were selected for containing them; companion-inclusive counts are
reported alongside for transparency.
A Monte Carlo set of random control fields — generated by
offsetting each host position by a fixed distance at seeded
random position angles — is queried identically, producing an
empirical field quasar surface density from the same catalogue.
The comparison tests the null hypothesis that Arp host fields
are ordinary lines of sight.

Simbad and VizieR are CDS services; the step does not depend on
NED availability.  Random field positions are generated with a
fixed seed for reproducibility.

Outputs:
    results/outputs/step_22_quasar_galaxy_association.json
    data/processed/qso_host_counts.csv
    data/processed/qso_field_counts.csv
    data/processed/qso_field_members.csv
        (member-level table: every confirmed quasar-class row in every
        host and control cone, with catalogue type and redshift —
        consumed by step_26 for the X-ray-selected density and the
        empirical field redshift distribution)
"""

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from astropy import units as u
from astropy.coordinates import SkyCoord

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.utils.logger import TEPLogger, set_step_logger, print_status
from scripts.utils.jsonio import json_safe

N_RANDOM_FIELDS = 12          # control fields per host
RANDOM_OFFSET_DEG = 1.5       # control field offset from host
SEARCH_RADIUS_ARCMIN = 6.0    # cone-search radius
QUERY_TIMEOUT = 60            # per-query timeout (seconds)
RNG_SEED = 20260924

MILLIQUAS_CATALOG = "VII/290/catalog"   # Flesch 2021, Million Quasars


CONFIRMED_CLASSES = ("Q", "A", "B", "K")

# Confirmed quasar-class totals published in the Milliquas v7.2
# ReadMe (VII/290, note 3): Q = 790776, A = 38890, B = 2704,
# K = 5316.  Used to place the measured field density on the
# all-sky catalogue scale.
CLASS_COUNTS_ALLSKY = {"Q": 790776, "A": 38890, "B": 2704, "K": 5316}
SKY_AREA_DEG2 = 41252.96124941927      # 4 pi steradians in deg^2


def is_confirmed_quasar(type_str):
    """Milliquas quasar-class membership (VII/290 ReadMe, note 3):
    the first character encodes the spectroscopic class and the
    remaining characters are association flags (R = radio,
    X = X-ray, 2 = double radio lobes).  Confirmed quasar-class
    objects are type-I broad-line QSOs (Q), type-I Seyfert/AGN
    nuclei (A), BL Lac objects (B), and type-II narrow-line
    quasars (K).  Excluded: N (type-II Seyfert/NELG, which the
    catalogue documents as carrying a residue of legacy
    NELGs/ELGs/LINERs), L (lensed extra images, not independent
    objects), and all candidates (lowercase classes and rows
    whose Type carries only association flags, e.g. 'X', 'RX')."""
    t = str(type_str).strip()
    return len(t) > 0 and t[0] in CONFIRMED_CLASSES


def _normalise_name(name):
    """Normalise a catalogue name for host-matching: uppercase
    and strip all whitespace ('NGC 7603' -> 'NGC7603')."""
    return "".join(str(name).split()).upper()


class Step22QuasarGalaxyAssociation:
    """Step 22: Empirical quasar overdensity around Arp hosts."""

    def __init__(self):
        self.root = PROJECT_ROOT
        self.data_processed = self.root / "data" / "processed"
        self.results = self.root / "results" / "outputs"
        self.logs = self.root / "logs"

        for d in [self.data_processed, self.results, self.logs]:
            d.mkdir(parents=True, exist_ok=True)

        self.logger = TEPLogger(
            "step_22",
            log_file_path=self.logs / "step_22_quasar_galaxy_association.log",
        )
        set_step_logger(self.logger)

    def _resolve_host(self, name):
        """Resolve a host-galaxy name to J2000 coordinates via Simbad."""
        from astroquery.simbad import Simbad

        tbl = Simbad.query_object(name)
        if tbl is None or len(tbl) == 0:
            return None
        return SkyCoord(float(tbl[0]["ra"]) * u.deg, float(tbl[0]["dec"]) * u.deg)

    def _query_qsos(self, coord, radius_arcmin, exclude_name=None):
        """Return the confirmed quasar-class Milliquas rows in a cone
        as a list of dicts (name, type, coord, offset_arcmin), or
        None on query failure.  The row whose catalogue Name matches
        exclude_name (whitespace-insensitive) is skipped, so the
        host galaxy's own Milliquas entry (e.g. NGC 7603, type 'ARX')
        is never counted toward its own field."""
        from astroquery.vizier import Vizier

        viz = Vizier(row_limit=-1, timeout=QUERY_TIMEOUT)
        for attempt in (1, 2):
            try:
                res = viz.query_region(
                    coord, radius=radius_arcmin * u.arcmin,
                    catalog=MILLIQUAS_CATALOG,
                )
                break
            except Exception as e:
                self.logger.warning(
                    f"VizieR region query failed (attempt {attempt}): {e}"
                )
                res = None
                if attempt == 2:
                    return None
                time.sleep(1.0)
        if res is None or MILLIQUAS_CATALOG not in res.keys():
            return []
        tbl = res[MILLIQUAS_CATALOG]
        if len(tbl) == 0:
            return []
        excl = _normalise_name(exclude_name) if exclude_name else None
        rows = []
        for r in tbl:
            if excl and _normalise_name(r["Name"]) == excl:
                continue
            if is_confirmed_quasar(r["Type"]):
                opos = SkyCoord(
                    ra=float(r["RAJ2000"]) * u.deg,
                    dec=float(r["DEJ2000"]) * u.deg,
                )
                # Milliquas z column: spectroscopic redshift where the
                # catalogue carries one; masked/NaN for rows without.
                try:
                    z_val = r["z"]
                    z_f = (
                        float(z_val)
                        if not np.ma.is_masked(z_val)
                        else np.nan
                    )
                except Exception:
                    z_f = np.nan
                rows.append({
                    "name": str(r["Name"]),
                    "type": str(r["Type"]),
                    "coord": opos,
                    "z": z_f,
                    "offset_arcmin": float(
                        coord.separation(opos).to(u.arcmin).value
                    ),
                })
        return rows

    def run(self):
        print_status("Running quasar-galaxy association test...", "PROCESS")

        catalog_path = self.data_processed / "arp_pair_catalog_verified.csv"
        if not catalog_path.exists():
            catalog_path = self.data_processed / "arp_pair_catalog.csv"
        if not catalog_path.exists():
            raise FileNotFoundError(
                f"Pair catalog not found: {catalog_path}. Run step_00 first."
            )
        catalog = pd.read_csv(catalog_path)

        # Catalogued companion positions resolved by step_20 are used
        # to remove the companions themselves from the host counts:
        # the pairs were selected for containing these objects, so
        # counting them toward the overdensity would be circular.
        # The companion-inclusive counts are still reported alongside.
        comp_coords = {}
        comp_path = self.data_processed / "companion_positions.csv"
        if comp_path.exists():
            dfc = pd.read_csv(comp_path)
            for pid, grp in dfc.groupby("pair_id"):
                comp_coords[pid] = [
                    SkyCoord(ra=r.ra_deg * u.deg, dec=r.dec_deg * u.deg)
                    for r in grp.itertuples()
                ]
            print_status(
                f"Companion exclusion list loaded for "
                f"{len(comp_coords)} pairs "
                f"({sum(len(v) for v in comp_coords.values())} objects).",
                "INFO",
            )
        else:
            self.logger.warning(
                "companion_positions.csv not found; run step_20 first. "
                "Falling back to companion-inclusive counts only."
            )

        rng = np.random.default_rng(RNG_SEED)
        host_records = []
        field_records = []
        member_records = []

        for _, row in catalog.iterrows():
            pair_id = row["pair_id"]
            try:
                gpos = self._resolve_host(row["galaxy"])
            except Exception as e:
                self.logger.warning(f"Simbad resolve failed {row['galaxy']}: {e}")
                gpos = None
            if gpos is None:
                continue

            # Single cone query; the companion-exclusive count removes
            # catalogued companions within 15 arcsec of a resolved
            # position (non-circular primary count).
            rows_q = self._query_qsos(
                gpos, SEARCH_RADIUS_ARCMIN, exclude_name=row["galaxy"]
            )
            if rows_q is None:
                continue
            excl_coords = comp_coords.get(pair_id, [])
            n_all = len(rows_q)
            kept = []
            dropped = []
            for q in rows_q:
                if any(
                    q["coord"].separation(ec).to(u.arcsec).value < 15.0
                    for ec in excl_coords
                ):
                    dropped.append(q["name"])
                else:
                    kept.append(q)
            n_excl = len(kept)
            names = [q["name"] for q in kept]
            types = [q["type"] for q in kept]
            offsets = [q["offset_arcmin"] for q in kept]
            host_records.append({
                "pair_id": pair_id,
                "n_qso": n_excl,
                "n_qso_inclusive": n_all,
                "companions_excluded": ";".join(dropped),
                "qso_names": ";".join(names), "qso_types": ";".join(types),
                "qso_offsets_arcmin": ";".join(f"{o:.3f}" for o in offsets),
            })
            for q in rows_q:
                member_records.append({
                    "pair_id": pair_id,
                    "field_kind": "host",
                    "field_index": -1,
                    "is_catalogued_companion": q["name"] in dropped,
                    "name": q["name"],
                    "type": q["type"],
                    "z": q["z"],
                    "offset_arcmin": q["offset_arcmin"],
                })
            print_status(
                f"{pair_id}: {n_excl} confirmed quasars within "
                f"{SEARCH_RADIUS_ARCMIN:.0f} arcmin "
                f"({n_all} companion-inclusive; excluded: "
                f"{'; '.join(dropped) if dropped else 'none'})",
                "TEST",
            )
            time.sleep(0.4)

            # Random control fields
            for k in range(N_RANDOM_FIELDS):
                pa = rng.uniform(0, 360.0)
                dec_off = RANDOM_OFFSET_DEG * np.sin(np.radians(pa))
                ra_off = (
                    RANDOM_OFFSET_DEG
                    * np.cos(np.radians(pa))
                    / np.cos(gpos.dec.radian)
                )
                cpos = SkyCoord(
                    ra=(gpos.ra.deg + ra_off) * u.deg,
                    dec=(gpos.dec.deg + dec_off) * u.deg,
                )
                rows_f = self._query_qsos(cpos, SEARCH_RADIUS_ARCMIN)
                n_f = len(rows_f) if rows_f is not None else None
                if n_f is not None:
                    field_records.append({
                        "pair_id": pair_id, "field_index": k, "n_qso": n_f,
                    })
                    for q in rows_f:
                        member_records.append({
                            "pair_id": pair_id,
                            "field_kind": "control",
                            "field_index": k,
                            "is_catalogued_companion": False,
                            "name": q["name"],
                            "type": q["type"],
                            "z": q["z"],
                            "offset_arcmin": q["offset_arcmin"],
                        })
                time.sleep(0.25)

        dfh = pd.DataFrame(host_records)
        dff = pd.DataFrame(field_records)
        dfm = pd.DataFrame(member_records)
        dfh.to_csv(self.data_processed / "qso_host_counts.csv", index=False)
        dff.to_csv(self.data_processed / "qso_field_counts.csv", index=False)
        dfm.to_csv(self.data_processed / "qso_field_members.csv", index=False)
        print_status(
            f"Saved member-level table: qso_field_members.csv "
            f"({len(dfm)} confirmed quasar-class rows across "
            f"{len(dff)} control fields + {len(dfh)} host cones).",
            "SUCCESS",
        )

        if len(dff) < 20:
            raise RuntimeError(
                "Too few control fields queried; archive unreachable. "
                "Refusing to compute association statistics."
            )

        # Empirical comparison
        mean_field = float(dff["n_qso"].mean())
        std_field = float(dff["n_qso"].std(ddof=1))
        host_vals = dfh["n_qso"].to_numpy(dtype=float)
        mean_host = float(host_vals.mean())
        excess = mean_host - mean_field
        sigma = excess / std_field if std_field > 0 else np.nan

        # Poisson probability each host has at least its count
        from scipy.stats import poisson

        dfh["p_poisson"] = [
            float(1.0 - poisson.cdf(int(n) - 1, mean_field)) for n in host_vals
        ]

        # Empirical p-value: fraction of pooled control fields with a
        # count at least as large as the host's (the field distribution
        # is overdispersed relative to Poisson, so the empirical tail
        # is the honest null).
        field_vals = dff["n_qso"].to_numpy(dtype=float)
        n_f = len(field_vals)
        dfh["p_empirical"] = [
            float((1.0 + np.sum(field_vals >= n)) / (1.0 + n_f))
            for n in host_vals
        ]
        # Pooled Poisson test of the host total against the field rate
        p_pooled = float(
            1.0 - poisson.cdf(int(host_vals.sum()) - 1, mean_field * len(host_vals))
        )
        # The same pooled tail for the companion-inclusive total: the
        # ensemble excess carried by the catalogued companions
        # themselves, priced directly rather than asserted.
        n_incl = (
            int(dfh["n_qso_inclusive"].sum())
            if "n_qso_inclusive" in dfh.columns else None
        )
        p_pooled_inclusive = (
            float(1.0 - poisson.cdf(n_incl - 1, mean_field * len(host_vals)))
            if n_incl is not None else None
        )

        # Paired per-host comparison: each host against only its own
        # 12 control fields.  The pooled control distribution mixes
        # sight-lines of differing catalogue completeness (e.g. the
        # NGC 4319 controls lie off the main spectroscopic footprint
        # and return zero confirmed objects), so the paired test is
        # the completeness-robust null.  Per-host empirical tail:
        # fraction of that host's own controls with count >= host.
        from scipy.stats import chi2 as _chi2, wilcoxon as _wilcoxon

        paired = []
        p_own_list = []
        diffs = []
        for rec in host_records:
            pid = rec["pair_id"]
            own = dff.loc[dff["pair_id"] == pid, "n_qso"].to_numpy(dtype=float)
            n_own = len(own)
            p_own = float((1.0 + np.sum(own >= rec["n_qso"])) / (1.0 + n_own))
            paired.append({
                "pair_id": pid,
                "n_qso": int(rec["n_qso"]),
                "own_control_mean": float(own.mean()) if n_own else None,
                "own_control_max": float(own.max()) if n_own else None,
                "n_own_controls_ge_host": int(np.sum(own >= rec["n_qso"])),
                "p_empirical_own_controls": p_own,
            })
            p_own_list.append(p_own)
            diffs.append(rec["n_qso"] - (own.mean() if n_own else 0.0))
            rec["p_empirical_own_controls"] = p_own

        p_arr = np.clip(np.asarray(p_own_list), 1e-12, 1.0)
        fisher_stat = float(-2.0 * np.sum(np.log(p_arr)))
        p_fisher = float(1.0 - _chi2.cdf(fisher_stat, 2 * len(p_arr)))
        try:
            import warnings as _warnings
            with _warnings.catch_warnings(record=True) as caught:
                _warnings.simplefilter("always")
                w_res = _wilcoxon(diffs, alternative="greater")
            for _w in caught:
                self.logger.info(
                    f"wilcoxon note: {str(_w.message).strip()}"
                )
            p_wilcoxon = float(w_res.pvalue)
        except Exception:
            p_wilcoxon = None
        n_hosts_exceed_own = int(sum(1 for p in p_own_list if p <= 0.1))

        # All-sky reference: catalogue surface density of the same
        # confirmed classes over the full celestial sphere, converted
        # to the expected count per search cone.
        field_area_deg2 = np.pi * (SEARCH_RADIUS_ARCMIN / 60.0) ** 2
        n_confirmed_allsky = sum(CLASS_COUNTS_ALLSKY.values())
        allsky_density = n_confirmed_allsky / SKY_AREA_DEG2
        allsky_lambda = allsky_density * field_area_deg2

        print_status(
            f"Field QSO density: {mean_field:.2f} +/- {std_field:.2f} per field",
            "TEST",
        )
        print_status(
            f"Host QSO counts mean: {mean_host:.2f}; excess = {excess:.2f} "
            f"({sigma:.2f} sigma of field scatter)", "TEST",
        )

        summary = {
            "search_radius_arcmin": SEARCH_RADIUS_ARCMIN,
            "n_random_fields_total": len(dff),
            "field_mean_qso": mean_field,
            "field_std_qso": std_field,
            "host_mean_qso": mean_host,
            "host_total_qso": int(host_vals.sum()),
            "host_mean_qso_inclusive": (
                float(dfh["n_qso_inclusive"].mean())
                if "n_qso_inclusive" in dfh.columns else None
            ),
            "host_total_qso_inclusive": (
                int(dfh["n_qso_inclusive"].sum())
                if "n_qso_inclusive" in dfh.columns else None
            ),
            "companions_excluded_from_host_counts": bool(comp_coords),
            "excess_sigma_of_field_scatter": float(sigma),
            "p_pooled_poisson": p_pooled,
            "p_pooled_poisson_inclusive": p_pooled_inclusive,
            "paired_test": {
                "description": (
                    "Each host compared only against its own 12 seeded "
                    "control fields (completeness-robust null); empirical "
                    "tail p = (1 + #{own controls >= host})/(1 + 12); "
                    "combined across pairs by Fisher's method."
                ),
                "per_host": paired,
                "n_hosts_exceed_all_own_controls_p01": n_hosts_exceed_own,
                "fisher_chi2": fisher_stat,
                "p_fisher_combined": p_fisher,
                "p_wilcoxon_host_vs_own_controls": p_wilcoxon,
            },
            "allsky_confirmed_density_deg2": float(allsky_density),
            "allsky_expected_per_field": float(allsky_lambda),
            "field_to_allsky_ratio": float(mean_field / allsky_lambda),
            "hosts": dfh.to_dict(orient="records"),
            "rng_seed": RNG_SEED,
            "catalog": "Milliquas v7.2 (VizieR VII/290; Flesch 2021)",
            "quasar_definition": (
                "Milliquas spectroscopic classes Q, A, B, K (confirmed "
                "quasar-class: type-I QSO, type-I Seyfert/AGN, BL Lac, "
                "type-II quasar); N-class (NELG/LINER residue), L "
                "(lensed images) and candidates excluded; the host "
                "galaxy's own catalogue entry removed by name, and "
                "catalogued companions removed by position "
                "(non-circular primary count)."
            ),
            "method": (
                "Simbad host resolution; VizieR cone-search counts of "
                f"confirmed quasar-class objects within {SEARCH_RADIUS_ARCMIN} "
                f"arcmin of each host vs {N_RANDOM_FIELDS} seeded random "
                "offset fields per host. Primary counts exclude the "
                "catalogued companions (step_20 archive positions, 15 "
                "arcsec exclusion) so the selection objects do not "
                "inflate the overdensity; companion-inclusive counts "
                "are reported alongside."
            ),
        }
        json_path = self.results / "step_22_quasar_galaxy_association.json"
        with open(json_path, "w") as f:
            json.dump(json_safe(summary), f, indent=2)
        print_status(f"Saved JSON: {json_path}", "SUCCESS")
        print_status("Quasar-galaxy association test complete.", "SUCCESS")
