#!/usr/bin/env python3
"""
Step 10: Intrinsic Conformal Factor
===================================
Computes the TEP intrinsic conformal factor A_int(Q) for every
discordant pair in the catalog.

Under TEP the observed redshift of an object is a product of the
background temporal shear accumulated over the path, A_bg(r), and
the local shear generated by the object's own proper-time field,
A_int:

    1 + z = A_0 / (A_bg(r) * A_int)

For two objects sharing the same spatial coordinate distance r
the background factor divides out exactly:

    (1 + z_Q) / (1 + z_G) = 1 / A_int(Q)

so that A_int(Q) = (1 + z_G) / (1 + z_Q) and the local
proper-time offset is

    Delta phi = phi_Q - phi_G = -ln A_int(Q)   (beta_A = -1, M_Pl units)

This is the central diagnostic of the paper: a measurable,
distance-independent quantification of the local proper-time
gradient of the companion.

Outputs:
    results/outputs/step_10_intrinsic_conformal_factor.json
    data/processed/intrinsic_conformal_factors.csv
"""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.utils.logger import TEPLogger, set_step_logger, print_status
from scripts.utils.jsonio import json_safe


class Step10IntrinsicConformalFactor:
    """Step 10: Compute A_int(Q) for each discordant pair."""

    def __init__(self):
        self.root = PROJECT_ROOT
        self.data_processed = self.root / "data" / "processed"
        self.results = self.root / "results" / "outputs"
        self.logs = self.root / "logs"

        for d in [self.data_processed, self.results, self.logs]:
            d.mkdir(parents=True, exist_ok=True)

        self.logger = TEPLogger(
            "step_10",
            log_file_path=self.logs / "step_10_intrinsic_conformal_factor.log",
        )
        set_step_logger(self.logger)

    def run(self):
        print_status("Computing intrinsic conformal factors...", "PROCESS")

        # Prefer NED-verified catalog when available
        catalog_path = self.data_processed / "arp_pair_catalog_verified.csv"
        if not catalog_path.exists():
            catalog_path = self.data_processed / "arp_pair_catalog.csv"
        if not catalog_path.exists():
            raise FileNotFoundError(
                f"Pair catalog not found: {catalog_path}. Run step_00 first."
            )
        catalog = pd.read_csv(catalog_path)
        print_status(f"Loaded {len(catalog)} pairs from {catalog_path.name}", "PROCESS")

        rows = []
        for _, row in catalog.iterrows():
            z_g, z_q = float(row["z_gal"]), float(row["z_comp"])

            a_int = (1.0 + z_g) / (1.0 + z_q)
            delta_phi = -np.log(a_int)
            z_intrinsic = (1.0 + z_q) / (1.0 + z_g) - 1.0
            clock_ratio = a_int  # companion clocks run at A_int of galaxy rate

            rows.append({
                "pair_id": row["pair_id"],
                "z_gal": z_g,
                "z_comp": z_q,
                "a_int": a_int,
                "delta_phi": delta_phi,
                "z_intrinsic": z_intrinsic,
                "clock_rate_ratio": clock_ratio,
                "hubble_distance_factor": z_q / z_g,
                "separation_arcsec": row["separation_arcsec"],
                "connection_type": row["connection_type"],
            })

            print_status(
                f"{row['pair_id']}: A_int={a_int:.4f}  "
                f"Delta_phi={delta_phi:.4f}  "
                f"z_intrinsic={z_intrinsic:.3f}",
                "TEST",
            )

        df = pd.DataFrame(rows)
        csv_path = self.data_processed / "intrinsic_conformal_factors.csv"
        df.to_csv(csv_path, index=False)
        print_status(f"Saved conformal factor table: {csv_path}", "SUCCESS")

        summary = {
            "formalism": {
                "redshift_decomposition": "1 + z = A_0 / (A_bg(r) * A_int)",
                "pair_ratio": "(1+z_Q)/(1+z_G) = 1/A_int(Q)",
                "coupling": "A(phi) = exp(beta_A * phi), beta_A = -1",
                "delta_phi": "Delta phi = phi_Q - phi_G = -ln A_int(Q)",
            },
            "n_pairs": len(df),
            "a_int_range": [float(df["a_int"].min()), float(df["a_int"].max())],
            "delta_phi_range": [
                float(df["delta_phi"].min()), float(df["delta_phi"].max())
            ],
            "pairs": rows,
        }

        json_path = self.results / "step_10_intrinsic_conformal_factor.json"
        with open(json_path, "w") as f:
            json.dump(json_safe(summary), f, indent=2)
        print_status(f"Saved JSON: {json_path}", "SUCCESS")
        print_status("Intrinsic conformal factors computed.", "SUCCESS")
